
# Server
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=postgres://u92jfafcpi3a2g:pb5bbb861303195409c2579d04fa468af16130b31c108725ee9b5b0094866afb5@cd62ai72qd7d5j.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d3rrtqgb88ssf
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# EMAIL (Gmail for Staff Alerts)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true